CouchbaseWebAppExample/Models/ActivityNode.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CouchbaseWebAppExample.Models
{
    public class ActivityNode
    {
        public static ConcurrentDictionary<string, ActivityNode> ParentChildRelationships =
            new ConcurrentDictionary<string, ActivityNode>();

        private Activity Activity { get; set; }

        public string Id => Activity.Id;
        public string OperationName => Activity.OperationName;
        public string DisplayName => Activity.DisplayName;

        public DateTimeOffset StartTimeUtc => Activity.StartTimeUtc;
        public TimeSpan Duration => Activity.Duration;

        public long DurationUs => (long) (Duration.TotalMilliseconds * 1000);

        public IEnumerable<KeyValuePair<string, string>> Tags => GetUniqueTags();

        public ConcurrentDictionary<string, ActivityNode> Children { get; } = new ConcurrentDictionary<string, ActivityNode>();

        private IEnumerable<KeyValuePair<string, string>> GetUniqueTags()
        {
            var uniqueTags = new Dictionary<string, string>();
            foreach (var kvp in Activity.Tags)
            {
                uniqueTags[kvp.Key] = kvp.Value;
            }

            return uniqueTags.OrderBy(kvp => kvp.Key);
        }

        public static void RecordStopActivity(Activity activity)
        {
            var thisNode = ParentChildRelationships.GetOrAdd(activity.Id, 
                a => new ActivityNode() { Activity = activity });

            var sanity = 0;
            while (thisNode.Activity.Parent != null 
                   && thisNode.Activity.Parent != thisNode.Activity
                   && sanity++ < 1000)
            {
                var thisNodeParent = thisNode.Activity.Parent;
                var parent =
                    ParentChildRelationships.GetOrAdd(thisNode.Activity.Parent.Id,
                        a => new ActivityNode() { Activity = thisNodeParent });

                parent.Children.GetOrAdd(thisNode.Activity.Id, thisNode);

                thisNode = parent;
            }
        }
    }
}

CouchbaseWebAppExample/Controllers/AirlineController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Couchbase;
using Couchbase.Core.Exceptions.KeyValue;
using Couchbase.Extensions.DependencyInjection;
using Couchbase.KeyValue;
using CouchbaseWebAppExample.Buckets;
using CouchbaseWebAppExample.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;

namespace CouchbaseWebAppExample.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public sealed class AirlineController : Controller
    {
        private readonly IBucketProvider _bucketProvider;
        private readonly IClusterProvider _clusterProvider;
        private readonly ITravelSample _travelSample;
        private readonly IMembucket _membucket;
        private const string BucketName = @"travel-sample";

        private static DiagnosticListener DiagListener = new DiagnosticListener("AirlineController");

        public AirlineController(
            IBucketProvider bucketProvider, 
            IClusterProvider clusterProvider, 
            ITravelSample travelSample, 
            IMembucket membucket)
        {
            _bucketProvider = bucketProvider;
            _clusterProvider = clusterProvider;
            _travelSample = travelSample;
            _membucket = membucket;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            using var span =
                DiagListener.StartActivity(new Activity(nameof(AirlineController) + "." + nameof(Index)), null);
            var bucket = await _travelSample.GetBucketAsync().ConfigureAwait(false);
            var queryResults = await bucket.Cluster
                .QueryAsync<dynamic>("SELECT icao, name FROM `travel-sample` WHERE type = 'airline' ORDER BY name")
                .ConfigureAwait(false);
            var results = new List<(string icao, string name)>();
            await foreach (var qr in queryResults.Rows)
            {
                results.Add((qr.icao, qr.name));
            }
            
            DiagListener.StopActivity(span, null);
            return View(results);
        }

        [HttpGet("{icao}")]
        public async Task<IActionResult> Get(string icao)
        {
            using var span = 
                DiagListener.StartActivity(new Activity(nameof(AirlineController) + "." + nameof(Get)), new { icao });
            Airline airline;
            var membucket = await _membucket.GetBucketAsync().ConfigureAwait(false);
            var memCollection = membucket.DefaultCollection();
            var travelSampleBucket = await _travelSample.GetBucketAsync().ConfigureAwait(false);
            var collection = travelSampleBucket.DefaultCollection();
            if (int.TryParse(icao, out var id))
            {
                var fullId = $"airline_{id}";
                var getResult = await collection.GetAsync(fullId).ConfigureAwait(false);
                airline = getResult.ContentAs<Airline>();
            }
            else
            {
                try
                {
                    var memGetResult = await memCollection.GetAsync(icao).ConfigureAwait(false);
                    airline = memGetResult.ContentAs<Airline>();
                    if (airline.Name == null)
                    {
                        throw new DocumentNotFoundException();
                    }

                    return View(airline);
                }
                catch (DocumentNotFoundException)
                {
                    var cluster = await _clusterProvider.GetClusterAsync().ConfigureAwait(false);
                    var queryResult = await cluster.QueryAsync<Airline>(
                        "SELECT `travel-sample`.* FROM `travel-sample` WHERE type='airline' AND icao = $icao",
                        options => options.Parameter("icao", icao)).ConfigureAwait(false);
                    airline = await queryResult.Rows.FirstOrDefaultAsync().ConfigureAwait(false);
                }
            }

            if (airline == null)
            {
                return NotFound();
            }

            if (airline?.Icao != null)
            {
                var memUpsertResult = await memCollection.UpsertAsync<Airline>(airline.Icao, airline, options => options.Expiry(TimeSpan.FromSeconds(30)));
            }

            return View(airline);
        }

        // POST: api/TravelSample
        [HttpPost]
        public void Post([FromBody] string value)
        {
        }

        // PUT: api/TravelSample/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

CouchbaseWebAppExample/Controllers/TraceViewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CouchbaseWebAppExample.Models;
using Microsoft.AspNetCore.Mvc;

namespace CouchbaseWebAppExample.Controllers
{
    [Route("/trace")]
    [Controller]
    public class TraceViewerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("{activityId}")]
        public IActionResult Get(string activityId)
        {
            if (ActivityNode.ParentChildRelationships.TryGetValue(activityId, out var node))
            {
                return View(node);
            }

            return NotFound();
        }
    }
}

CouchbaseWebAppExample/Views/TraceViewer/ActivityNode.cshtml
@model CouchbaseWebAppExample.Models.ActivityNode

    <div class="ActivityNode @Model.OperationName">
        <div class="OperationName">@Model.DisplayName (<code>@Model.Id</code>)</div>
        <div class="duration" style="width : @((int)Model.Duration.TotalMilliseconds)px">&nbsp;</div>
        <dl>
            <dt>Start</dt><dd>@Model.StartTimeUtc.ToLocalTime()</dd>
            <dt>Duration</dt><dd>@Model.DurationUs&micro;s</dd>
            @foreach (var tag in @Model.Tags)
            {
                <dt class="tagName">@tag.Key</dt>
                <dd class="tagValue">@tag.Value</dd>
            }
        </dl>
        <ul class="child-nodes">@foreach (var child in @Model.Children.Values.OrderBy(v => v.StartTimeUtc))
        {
            <li>
            @await Html.PartialAsync("ActivityNode", child)
            </li>
        }</ul>
    </div>

CouchbaseWebAppExample/Views/TraceViewer/Get.cshtml
@model CouchbaseWebAppExample.Models.ActivityNode
@using System.Diagnostics
@using CouchbaseWebAppExample.Models
@using Newtonsoft.Json.Linq
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<style>
    .ActivityNode {
        display: flex;
        flex-direction: column;
        border : 1px dotted black;
        padding : 0.25em;
    }

    .ActivityNode .duration {
        background-color: green;
    }

    .ActivityNode .OperationName {
        font-weight : bold;
    }

    .ActivityNode dl {
        display: flex;
        flex-flow: row wrap;
        border: solid #333;
        border-width: 1px 1px 0 0;
    }
    .ActivityNode dt {
        flex-basis: 20%;
        padding: 0.1em 0.2em text-align: right;
    }
    .ActivityNode dd {
        flex-basis: 70%;
        flex-grow: 1;
        margin: 0;
        padding: 0.1em 0.2em;
    }
</style>
<h1>Trace Viewer</h1>

<h2>@Model.OperationName (@Model.Id)</h2>

<partial name="ActivityNode" model="Model"/>

CouchbaseWebAppExample/Views/TraceViewer/Index.cshtml
@using System.Diagnostics
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Trace Viewer</h1>

<h2>Recent Traces</h2>

<ul>
    <li><a asp-controller="Airline" asp-action="Index">Airlines</a></li>
</ul>

@Activity.Current.Id (@Activity.Current.OperationName)